# Notice the image: line for each service
# Normal docker compose nami convention will cause it to prepend the image
# name with the project (in my case it would do srcs-nginx, fo example).
# You can specify it to use a particular name for each image so I
# can have them withut the prepend
# but if dockerhub has an image of the same name docker compose up
# will attempt to pull the latest version from dockerhub, which we don't want.
# You can make sure this doesn't happen by either having an image locally
# of the same name, or by using the "--pull never" option (This is what I do)
services:
  nginx:
    build:
      context: requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
    restart: always

  wordpress:
    build:
      context: requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_vol:/var/www/html
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
#-----------------
networks:
  inception:
    driver: bridge
#--------------------
volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DIR}
  wp_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_DIR}
