services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/acourtar/data/mariadb
  wp_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/acourtar/data/wordpress
